### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by Sugapriyan-P-K** [easonliao1994/django_central_wallet#1]
You forgot to hide your django security key in the django_central_wallet application and this is a same mistake that i do in my first django application when i posted in github. 

> little tip you can create a another python file and import it in settings.py and call a function or secret key by the import module and put the module name in .gitignore

**Comment by easonliao1994** [comment]
Hey @Sugapriyan-P-K ,

Thanks for bringing this issue to my attention. I'm sorry for the mistake of not hiding the Django security key in the django_central_wallet application. I've fixed the problem and taken steps to ensure the security of the application.

Apologies for any inconvenience caused. I appreciate your report and will be more careful in the future.

Best regards,
Eason
